"""initial_commit

Revision ID: ca3b85d5a83b
Revises: 
Create Date: 2025-07-01 23:09:24.508445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca3b85d5a83b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_is_processed', 'assets', ['is_processed'], unique=False)
    op.create_index('ix_asset_project_id', 'assets', ['asset_project_id'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('ix_chunk_asset_id', 'chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunk_project_id', 'chunks', ['chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_project_id', table_name='chunks')
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.drop_index('ix_asset_is_processed', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
